---
title: "Ch 22 Text Mining"
output:
  html_document:
    df_print: paged
    number_sections: true
    toc: true
    pandoc_args: [
      "--number-sections",
      "--number-offset=21"
    ]
---


<!-- run: *Cmd+Shift+Enter* -->

<!-- insert: *Cmd+Option+I* -->

<!-- knit: *Cmd+Shift+K* -->

## Trum tweets analysis

```{r}
library(tidyverse)
library(lubridate)
library(scales)
```

Get data from the website trumptwitterarchive.com.
However, this data is already included in the `dslabs` package

```{r, eval=FALSE}
url <- 'http://www.trumptwitterarchive.com/data/realdonaldtrump/%s.json'
trump_tweets <- map(2009:2017, ~sprintf(url, .x)) %>%
  map_df(jsonlite::fromJSON, simplifyDataFrame = TRUE) %>%
  filter(!is_retweet & !str_detect(text, '^"')) %>%
  mutate(created_at = parse_date_time(created_at, orders = "a b! d! H!:M!:S! z!* Y!",tz="EST")) 
trump_tweets
```

```{r}
library(dslabs)
data("trump_tweets")
head(trump_tweets)
names(trump_tweets)
```

Tweet example.

```{r}
trump_tweets$text[16413] %>% str_wrap() %>% cat
```

Which device was used for the twitter account?
```{r}
trump_tweets %>% count(source) %>% arrange(desc(n)) #%>% head(5)
```

Focus on time of the campaign.
```{r}
campaign_tweets <- trump_tweets %>% 
  extract(source, "source", "Twitter for (.*)") %>%
  filter(source %in% c("Android", "iPhone") &
           created_at >= ymd("2015-06-17") & 
           created_at < ymd("2016-11-08")) %>%
  filter(!is_retweet) %>%
  arrange(created_at)
count(campaign_tweets)
```

Plot the divices Android and iPhone versus time.

```{r}
ds_theme_set()
campaign_tweets %>%
  mutate(hour = hour(with_tz(created_at, "EST"))) %>%
  count(source, hour) %>%
  group_by(source) %>%
  mutate(percent = n / sum(n)) %>%
  ungroup %>%
  ggplot(aes(hour, percent, color = source)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(labels = percent_format()) +
  labs(x = "Hour of day (EST)", y = "% of tweets", color = "")
```

## Text as data


Example for the `tidytext` package.
```{r}
library(tidyverse)
library(tidytext)
poem <- c("Roses are red,", "Violets are blue,", "Sugar is sweet,", "And so are you.")
example <- data_frame(line = c(1, 2, 3, 4), text = poem)
example
example %>% unnest_tokens(word, text)
```
